### ISSUE TITLE
Open source the smart contracts code of the auction demo/example

### ISSUE THREAD

**Issue by limcheekin** [y-pakorn/flutter_web3_auction#2]
Thanks for your kindness of open source the code, it is very helpful example on how to use the flutter_web3 package.

It will be great if you could open source the smart contracts solidity source code of the demo/example.

Hope to hear from you soon! :)

**Comment by y-pakorn** [comment]
Sounds good, but the contract is pretty unoptimized and outdated now so keep that in mind.
https://github.com/y-pakorn/flutter_web3_auction/tree/master/contracts
